version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    groups:
      angular:
        patterns:
          - "@angular/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
