version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "ngx-infinite-scroll"
      typescript-eslint:
         patterns:
           - "@typescript-eslint/*"

      angular-eslint:
        patterns:
          - "@angular-eslint/*"
          - "@typescript-eslint/utils"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
