version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      groups:
        angular-dependencies:
          patterns:
            - "@angular/*"
        other-dependencies:
          patterns:
            - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
